version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0


workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: build/Dockerfile
          no-output-timeout: 20m
          path: .
          profile-name: default
          region: AWS_REGION
          repo: backend
          tag: "latest,$CIRCLE_SHA1"
          filters:
           branches:
             only: main
