version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  #https://circleci.com/developer/orbs/orb/circleci/aws-cli
  aws-cli: circleci/aws-cli@3.1.3

jobs:
  build:
#    working_directory: /app
    
    docker:
#      - image: docker:20.10.21-git
      - image: "cimg/base:stable"
       
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/install
      - aws-cli/setup
      #- run:
      #   name: Setup VirtualEnv
      #      echo 'export IMAGE_NAME=hello-docker' >> $BASH_ENV 
      
      - run:
          name: Build image
          command: |
              #COMMIT_ID=$(git rev-list --tags --date-order | head -1)
              #TAG=$(git show-ref --tags | grep $COMMIT_ID | awk -F / '{print $NF}')
              docker build -t backend -f build/Dockerfile .
      - run:        
          name: push
          command: |
            docker images
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 197240313557.dkr.ecr.us-east-1.amazonaws.com
            docker tag backend:latest 197240313557.dkr.ecr.us-east-1.amazonaws.com/backend:latest
            docker push 197240313557.dkr.ecr.us-east-1.amazonaws.com/backend:latest
   
workflows:
  build_and_push_image:
    jobs:
      - build
