version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@2.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run: 
         name: env
         command: |
            echo "export COMMIT_ID=$(git rev-list --tags --date-order | head -1)" >> $BASH_ENV
            echo "export TAG=$(git show-ref --tags | grep $COMMIT_ID | awk -F / '{print $NF}')" >> $BASH_ENV

workflows:
  build_and_push_image:
    jobs:
      
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: build/Dockerfile
          path: .
          profile-name: default
          region: AWS_DEFAULT_REGION
          repo: backend
          tag: "latest,$CIRCLE_SHA1,$increment_tag"
          filters:
           tags:
             only: /.*/
      - build
        